### ISSUE TITLE
Базовые наработки по серверной части

### ISSUE THREAD

**Issue by MikAleinik** [MikAleinik/RSClone#10]
Скинуть ссылку на репозиторий или примеры кода

**Comment by freemandb** [comment]
Вот реализованный на fastify фреймворке полный CRUD для клона трелло
Здесь все методы, которые нам могут понадобится для нашего сервера. Модель базы имеется, но реализована простым массивом, однако с асинхронным доступом. Надеюсь, это поможет быстрее прикрутить реальную базу

https://github.com/freemandb/nodejs2021Q4-service

**Comment by freemandb** [comment]
запустить сервер:
npm i
nmp start
