### ISSUE TITLE
Альтернативное API для карты

### ISSUE THREAD

**Issue by MikAleinik** [MikAleinik/RSClone#11]
1. Предложить/найти альтернативное API карты
2. Создать описание с ссылками для работы с API

**Comment by emp74ark** [comment]
Сейчас разбираюсь с OSM:
- Для отрисовки на странице - Leaflet: https://github.com/Leaflet/Leaflet (пока не подружил с webpack)
- Данные о точках брать с помощью osm api (GET /api/0.6/map?bbox=left,bottom,right,top)
- Для расчета маршрута - OpenTripPlanner: http://www.opentripplanner.org/ (еще не брался)

**Comment by MikAleinik** [comment]
Андрей @emp74ark по готовности - вноси сюда необходимые ссылки с описанием по (аналогично MapBox) необходимым нам действиям с картой. И закидывай в завершенное.
 
Круто, что нашлась альтернатива!
