### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by MikAleinik** [MikAleinik/RSClone#13]
Для локализации возможно, в нашем случае я знаю, два варианта:
1. Заморочиться и реализовать стандарт i18n. Есть на js библиотеки с реализациями.
2. Упростить и разместить на сервере контроллер, который по запросу отдает json со списком key/value для всех полей фронта.

Я за второй вариант. 
На клиенте при загрузке приложения идет обращение на сервер, получается json, из него заполняется объект содержащий все поля приложения, объект при обращении к нему с ключом отдает текущее содержимое значения. На фронте в названия полей никогда не вносится его содержание вручную, всегда вызов "знающего" объекта с запросом по ключу.

@freemandb @emp74ark высказываемся и принимаем решение.

**Comment by emp74ark** [comment]
Я не нашел золотой пули для локализации, или best practices по этому вопросу.

Решил, что когда худо-бедно будет готов макет сделать словарь в json формате, а в страницах вместо строковых данных указать ключи из него.

Чтобы не делать двойную работу, решил, что к этому вопросу вернусь, когда будет готов макет.

Можно прямо сейчас сделать кнопку для переключения интерфейса, которая не будет делать пока ничего.

**Comment by MikAleinik** [comment]
Базовая структура локализации создана.
