### ISSUE TITLE
RS документация

### ISSUE THREAD

**Issue by MikAleinik** [MikAleinik/RSClone#2]
Основное задание
https://github.com/rolling-scopes-school/tasks/blob/master/tasks/rsclone/rsclone.md

Информация по курсовому проекту
https://github.com/rolling-scopes-school/tasks/tree/master/stage2/modules/final-task

Форма регистрации ТЗ приложения
https://docs.google.com/spreadsheets/d/1jPYWzzMU4qoATUPHFbNpq3tpCHZRDjM6EiY2nuNEnFg/edit#gid=0

Техническое задание к проекту
https://docs.google.com/document/d/1X7KjbMAySo-2MtZcUlY34K26zlDTTz8s/edit?usp=sharing&ouid=101486332645382941882&rtpof=true&sd=true

Деплой сервера
Адрес - https://rs-clone-server.lm.r.appspot.com
Доки - https://rs-clone-server.lm.r.appspot.com/documentation

Структура БД (приложение starUML)
https://drive.google.com/file/d/133CcUuwaW5QZmYn-3eMhdsE8dURwoKsi/view?usp=sharing
Скрипт создания и тестового наполнения БД
https://drive.google.com/file/d/1doW7JxNu1p3EmWoycgogxUvox_2Kw78f/view?usp=sharing

База данных удаленная 
ruby.db.elephantsql.com
База - ofpofexk
Пользователь - ofpofexk
Пароль - m-80U-8RJaQjdmqeObQkJkwJ7Xcn6BCf

**Comment by emp74ark** [comment]
По тех-заданию:

- возможно стоит пока избегать указания конкретного поставщика карт (в тех задании указан MapBox). На данный момент я все делаю на основе OSM, но оставляю теоретическую возможность перескочить на другого поставщика геоданных, если будут проблемы. Я взял библиотеку leaflet, которая позволяет это сделать (по крайней мере в документации).
- Поисните пожалуйста выделенную часть текста: интерактивная карта пользователь имеет возможность просмотреть детальную информацию о каждом отображенном элементе карты в модальном окне, **информация на карте дублируется в табличном виде в дополнительном окне, при выборе элемента карты подсвечивается строка таблицы и наоборот**;

**Comment by MikAleinik** [comment]
1. Исправлю в ТЗ на два варианта апишки - MapBox и OSM. Какую библиотеку уже используем указывать не буду.
2. В данной вкладке кроме карты есть участок экрана для отображения текстовой информации (для грузоперевозчиков - таблица машин, для заказчиков - грузов). У пользователя 100 машин разбросанных по карте. Он может:
- кликнуть на машине по карте - в таблице подсвечивается нужная строка с данной машиной и если строка за пределами экрана, то таблица подкручивается на нее.
- кликнуть по строке в таблице - карта позиционируется на нужную машину и приближает масштаб до определенного размера.
@emp74ark
