### ISSUE TITLE
Файловая структура проекта

### ISSUE THREAD

**Issue by MikAleinik** [MikAleinik/RSClone#9]

**Comment by freemandb** [comment]
Предлагаю такую файловую структуру:

root:
client - клиентская часть
- |_src - сорсы
- - |_ types - возможные типы и интерфейсы
- - |_ com - компоненты
- - - |_ model - внутри класс(ы) модели
- - - |_ view
- - - - |_ com - компоненты вью
- - - - - |_ header   //пример
- - - - - - |_ header.ts
- - - - - - |_ header.css
- - - |_ controller
- - index.html
- - index.t
- конфиги для сборки, гитигнор, линтер, тс конфиг

server - по похожему приницу

**Comment by MikAleinik** [comment]
по клиенту - мне понятна такая структура, смогу в ней работать.
по серверу @freemandb для моего полного понимания такую структуру?

server
 - router - каталог роутера
 - - router.js
 - controller - каталог контроллеров
 - - authHandler - каталог обработчиков контроллера auth
 - - - success-auth-handler.js
 - - - fail-auth-handler.js
 - - auth.js
- model - каталог моделей
- - user.js
- - car.js
- data - каталог бд
- - data-mapper.js
- server.js
- конфиги для сборки, гитигнор, линтер
